databases:
  - name: api-productos-db
    databaseName: gestor_proyectos
    plan: free

services:
  - type: web
    name: api-productos
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 5051
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: api-productos-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: api-productos-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: api-productos-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: api-productos-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: api-productos-db
          property: password
